import { Artist, Producer, Release, Brand } from "@/types";

export const mockArtists: Artist[] = [
  {
    id: "1",
    name: "Phantom Waves",
    genre: "Hip-Hop / R&B",
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop",
    bio: "Phantom Waves is a boundary-pushing artist blending cinematic soundscapes with raw lyrical depth.",
    socialLinks: {
      instagram: "#",
      twitter: "#",
      spotify: "#",
    },
  },
  {
    id: "2",
    name: "Solara",
    genre: "Neo-Soul / Jazz",
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&h=400&fit=crop",
    bio: "Solara weaves neo-soul melodies with jazz-infused arrangements, creating music that transcends time.",
    socialLinks: {
      instagram: "#",
      spotify: "#",
    },
  },
  {
    id: "3",
    name: "Nyx Collective",
    genre: "Electronic / Trap",
    image: "https://images.unsplash.com/photo-1571974599782-87624638275e?w=400&h=400&fit=crop",
    bio: "A collective of electronic producers pushing the boundaries of trap and experimental sound design.",
    socialLinks: {
      instagram: "#",
      twitter: "#",
    },
  },
  {
    id: "4",
    name: "Aurelius",
    genre: "Rap / Conscious",
    image: "https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?w=400&h=400&fit=crop",
    bio: "Aurelius brings conscious rap to the mainstream, with introspective lyrics over golden-era beats.",
    socialLinks: {
      instagram: "#",
      spotify: "#",
    },
  },
  {
    id: "5",
    name: "Velvet Echo",
    genre: "Alternative R&B",
    image: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&h=400&fit=crop",
    bio: "Velvet Echo crafts atmospheric R&B experiences with lush vocals and dreamy production.",
    socialLinks: {
      instagram: "#",
      twitter: "#",
      spotify: "#",
    },
  },
  {
    id: "6",
    name: "Meridian",
    genre: "Afrobeat / Pop",
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=400&fit=crop",
    bio: "Meridian fuses Afrobeat rhythms with contemporary pop, creating infectious global anthems.",
    socialLinks: {
      spotify: "#",
      instagram: "#",
    },
  },
];

export const mockProducers: Producer[] = [
  {
    id: "1",
    name: "Throne Beats",
    specialty: "Hip-Hop / Trap",
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=400&h=400&fit=crop",
    bio: "Throne Beats has produced for some of the biggest names in hip-hop, known for hard-hitting 808s and melodic trap.",
    credits: ["Phantom Waves - Midnight Crown", "Aurelius - Gold Standard"],
  },
  {
    id: "2",
    name: "Nova Sound",
    specialty: "R&B / Neo-Soul",
    image: "https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?w=400&h=400&fit=crop",
    bio: "Nova Sound specializes in lush R&B and neo-soul production, with a signature warm analog sound.",
    credits: ["Solara - Celestial Dreams", "Velvet Echo - Midnight Blue"],
  },
  {
    id: "3",
    name: "Cipher 7",
    specialty: "Electronic / Experimental",
    image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=400&fit=crop",
    bio: "Cipher 7 pushes sonic boundaries with experimental electronic production and complex sound design.",
    credits: ["Nyx Collective - Void Frequencies", "Various Artists"],
  },
  {
    id: "4",
    name: "Golden Era",
    specialty: "Boom Bap / Classic Hip-Hop",
    image: "https://images.unsplash.com/photo-1516223725307-6f76b9182d6a?w=400&h=400&fit=crop",
    bio: "Golden Era brings classic boom bap sensibility to modern production, bridging eras with timeless beats.",
    credits: ["Aurelius - The Scroll", "Various Artists"],
  },
];

export const mockReleases: Release[] = [
  {
    id: "1",
    title: "Midnight Crown",
    artist: "Phantom Waves",
    coverArt: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400&fit=crop",
    releaseDate: "2024-11-15",
    type: "album",
    genre: "Hip-Hop",
    streamingLinks: { spotify: "#", appleMusic: "#" },
  },
  {
    id: "2",
    title: "Celestial Dreams",
    artist: "Solara",
    coverArt: "https://images.unsplash.com/photo-1504898770365-14faca6a7320?w=400&h=400&fit=crop",
    releaseDate: "2024-10-01",
    type: "ep",
    genre: "Neo-Soul",
    streamingLinks: { spotify: "#", youtube: "#" },
  },
  {
    id: "3",
    title: "Void Frequencies",
    artist: "Nyx Collective",
    coverArt: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop",
    releaseDate: "2024-09-20",
    type: "mixtape",
    genre: "Electronic",
    streamingLinks: { spotify: "#" },
  },
  {
    id: "4",
    title: "Gold Standard",
    artist: "Aurelius",
    coverArt: "https://images.unsplash.com/photo-1571974599782-87624638275e?w=400&h=400&fit=crop",
    releaseDate: "2024-08-05",
    type: "single",
    genre: "Conscious Rap",
    streamingLinks: { spotify: "#", appleMusic: "#", youtube: "#" },
  },
  {
    id: "5",
    title: "Midnight Blue",
    artist: "Velvet Echo",
    coverArt: "https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?w=400&h=400&fit=crop",
    releaseDate: "2024-07-12",
    type: "album",
    genre: "Alternative R&B",
    streamingLinks: { spotify: "#", appleMusic: "#" },
  },
  {
    id: "6",
    title: "Solar Winds",
    artist: "Meridian",
    coverArt: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=400&fit=crop",
    releaseDate: "2024-06-30",
    type: "ep",
    genre: "Afrobeat",
    streamingLinks: { spotify: "#", youtube: "#" },
  },
];

export const mockBrands: Brand[] = [
  {
    id: "1",
    name: "SUMG Apparel",
    description: "Premium streetwear and luxury fashion for the culture.",
    logo: "👕",
    category: "Fashion",
    url: "#",
  },
  {
    id: "2",
    name: "SUMG Studios",
    description: "State-of-the-art recording studios available for booking.",
    logo: "🎙️",
    category: "Recording",
    url: "#",
  },
  {
    id: "3",
    name: "SUMG Events",
    description: "Exclusive events, concerts, and listening parties.",
    logo: "🎪",
    category: "Events",
    url: "#",
  },
  {
    id: "4",
    name: "SUMG Publishing",
    description: "Music publishing and rights management services.",
    logo: "📜",
    category: "Publishing",
    url: "#",
  },
  {
    id: "5",
    name: "SUMG Media",
    description: "Content creation, music videos, and digital media.",
    logo: "🎬",
    category: "Media",
    url: "#",
  },
  {
    id: "6",
    name: "SUMG Academy",
    description: "Music education, mentorship, and artist development.",
    logo: "🎓",
    category: "Education",
    url: "#",
  },
];
