import { BrandTheme } from "@/lib/types";

export const brandThemes: Record<string, BrandTheme> = {
  woronoff: {
    slug: "woronoff",
    displayName: "Woronoff",
    heroStyle: "editorial",
    accentColor: "zinc",
    accentColorHex: "#a1a1aa",
    surfaceClassName: "bg-zinc-950 border border-zinc-800",
    cardClassName: "border border-zinc-800 bg-zinc-950 hover:border-zinc-600",
    buttonVariant: "border border-zinc-400 text-zinc-100 hover:bg-zinc-100 hover:text-black tracking-[0.3em] uppercase text-[10px] px-8 py-3",
    headingClassName: "font-black tracking-[-0.03em] text-white uppercase",
    bodyClassName: "text-zinc-400 text-sm leading-relaxed tracking-wide",
    gridStyle: "grid grid-cols-1 md:grid-cols-2 gap-px bg-zinc-800",
    borderStyle: "border-zinc-800",
    separatorStyle: "border-t border-zinc-800",
    backgroundStyle: "bg-zinc-950",
  },
  "unity-standard": {
    slug: "unity-standard",
    displayName: "Unity Standard",
    heroStyle: "minimal",
    accentColor: "sky",
    accentColorHex: "#38bdf8",
    surfaceClassName: "bg-neutral-950 border border-neutral-700/40",
    cardClassName: "border border-neutral-700/40 bg-neutral-950 hover:border-sky-900/60",
    buttonVariant: "border border-sky-800 text-sky-300 hover:bg-sky-900/30 tracking-[0.25em] uppercase text-[10px] font-mono px-8 py-3",
    headingClassName: "font-bold tracking-tight text-white font-mono",
    bodyClassName: "text-neutral-400 text-xs leading-loose tracking-widest font-mono",
    gridStyle: "grid grid-cols-1 md:grid-cols-3 gap-3",
    borderStyle: "border-neutral-700/40",
    separatorStyle: "border-t border-neutral-700/40",
    backgroundStyle: "bg-neutral-950",
  },
  "moon-spell": {
    slug: "moon-spell",
    displayName: "Moon Spell",
    heroStyle: "mystic",
    accentColor: "violet",
    accentColorHex: "#8b5cf6",
    surfaceClassName: "bg-[#0d0a1a] border border-violet-900/30",
    cardClassName: "border border-violet-900/30 bg-[#0d0a1a] hover:border-violet-600/50",
    buttonVariant: "border border-violet-700 text-violet-300 hover:bg-violet-900/40 tracking-[0.2em] uppercase text-[10px] px-8 py-3",
    headingClassName: "font-black tracking-tight text-violet-50 italic",
    bodyClassName: "text-violet-200/50 text-sm leading-relaxed tracking-wide",
    gridStyle: "grid grid-cols-1 md:grid-cols-2 gap-6",
    borderStyle: "border-violet-900/30",
    separatorStyle: "border-t border-violet-900/30",
    backgroundStyle: "bg-[#0d0a1a]",
  },
  "concrete-borough": {
    slug: "concrete-borough",
    displayName: "Concrete Borough",
    heroStyle: "industrial",
    accentColor: "stone",
    accentColorHex: "#78716c",
    surfaceClassName: "bg-stone-950 border border-stone-700",
    cardClassName: "border border-stone-700 bg-stone-950 hover:border-stone-400",
    buttonVariant: "bg-stone-800 text-stone-100 hover:bg-stone-700 tracking-[0.2em] uppercase text-[10px] font-black px-8 py-3",
    headingClassName: "font-black tracking-widest text-stone-100 uppercase",
    bodyClassName: "text-stone-400 text-sm leading-relaxed",
    gridStyle: "grid grid-cols-1 md:grid-cols-2 gap-1 bg-stone-800",
    borderStyle: "border-stone-700",
    separatorStyle: "border-t-2 border-stone-700",
    backgroundStyle: "bg-stone-950",
  },
  "salt-current": {
    slug: "salt-current",
    displayName: "Salt Current",
    heroStyle: "coastal",
    accentColor: "slate",
    accentColorHex: "#94a3b8",
    surfaceClassName: "bg-[#0c0e10] border border-slate-700/30",
    cardClassName: "border border-slate-700/30 bg-[#0c0e10] hover:border-slate-400/50",
    buttonVariant: "border border-slate-500 text-slate-200 hover:bg-slate-800/40 tracking-[0.3em] uppercase text-[10px] font-light px-8 py-3",
    headingClassName: "font-light tracking-[0.15em] text-slate-100 uppercase",
    bodyClassName: "text-slate-400 text-sm leading-loose tracking-widest font-light",
    gridStyle: "grid grid-cols-1 md:grid-cols-2 gap-8",
    borderStyle: "border-slate-700/30",
    separatorStyle: "border-t border-slate-700/30",
    backgroundStyle: "bg-[#0c0e10]",
  },
};

export function getBrandTheme(slug: string): BrandTheme {
  return brandThemes[slug] ?? brandThemes["woronoff"];
}
