import { CMSArtist, CMSProducer, CMSBrand, CMSRelease, CMSSong } from "@/lib/types";

export function rowToArtist(r: any): CMSArtist {
  return {
    id: r.id,
    slug: r.slug,
    name: r.name,
    role: r.role ?? "",
    genre: r.genre ?? "",
    bio: r.bio ?? "",
    longBio: r.long_bio ?? undefined,
    featured: r.featured ?? false,
    featuredOnHomepage: r.featured_on_homepage ?? false,
    tier: r.tier ?? "secondary",
    status: r.status ?? "active",
    sortOrder: r.sort_order ?? 0,
    heroImageUrl: r.hero_image_url ?? undefined,
    profileImageUrl: r.profile_image_url ?? undefined,
    socialLinks: r.social_links ?? undefined,
    shopUrl: r.shop_url ?? undefined,
    associatedBrands: r.associated_brands ?? undefined,
    providerConfig: r.provider_config ?? undefined,
    spotifyId: r.spotify_id ?? undefined,
    createdAt: r.created_at,
    updatedAt: r.updated_at,
  };
}

export function rowToProducer(r: any): CMSProducer {
  return {
    id: r.id,
    slug: r.slug,
    name: r.name,
    specialty: r.specialty ?? "",
    credits: r.credits ?? "",
    signature: r.signature ?? "",
    bio: r.bio ?? undefined,
    status: r.status ?? "active",
    sortOrder: r.sort_order ?? 0,
    featuredOnHomepage: r.featured_on_homepage ?? false,
    profileImageUrl: r.profile_image_url ?? undefined,
    heroImageUrl: r.hero_image_url ?? undefined,
    socialLinks: r.social_links ?? undefined,
    createdAt: r.created_at,
    updatedAt: r.updated_at,
  };
}

export function rowToBrand(r: any): CMSBrand {
  return {
    id: r.id,
    slug: r.slug,
    name: r.name,
    category: r.category ?? "",
    descriptor: r.descriptor ?? "",
    tagline: r.tagline ?? "",
    manifesto: r.manifesto ?? undefined,
    heroCopy: r.hero_copy ?? undefined,
    heroHeadline: r.hero_headline ?? undefined,
    heroSubcopy: r.hero_subcopy ?? undefined,
    longDescription: r.long_description ?? undefined,
    heroImageUrl: r.hero_image_url ?? undefined,
    logoUrl: r.logo_url ?? undefined,
    accentColor: r.accent_color ?? undefined,
    heroStyle: r.hero_style ?? undefined,
    campaignStatus: r.campaign_status ?? undefined,
    collectionName: r.collection_name ?? undefined,
    featuredReleaseSlugs: r.featured_release_slugs ?? undefined,
    featuredAssetIds: r.featured_asset_ids ?? undefined,
    isActive: r.is_active ?? true,
    featuredOnHomepage: r.featured_on_homepage ?? false,
    sortOrder: r.sort_order ?? 0,
    createdAt: r.created_at,
    updatedAt: r.updated_at,
  };
}

export function rowToRelease(r: any): CMSRelease {
  return {
    id: r.id,
    slug: r.slug,
    title: r.title,
    artistSlug: r.artist_slug,
    artistName: r.artist_name,
    featuredArtistSlugs: r.featured_artist_slugs ?? undefined,
    producerSlugs: r.producer_slugs ?? undefined,
    type: r.type ?? "Single",
    genre: r.genre ?? "",
    releaseDate: r.release_date,
    publishAt: r.publish_at ?? undefined,
    status: r.status ?? "draft",
    isVisible: r.is_visible ?? false,
    featuredOnHomepage: r.featured_on_homepage ?? false,
    description: r.description ?? "",
    coverArtUrl: r.cover_art_url ?? undefined,
    tracklist: r.tracklist ?? undefined,
    dspLinks: r.dsp_links ?? undefined,
    providerConfig: r.provider_config ?? undefined,
    rightsMetadata: r.rights_metadata ?? undefined,
    distributionRecord: r.distribution_record ?? undefined,
    dataSource: r.data_source ?? undefined,
    createdAt: r.created_at,
    updatedAt: r.updated_at,
  };
}

export function rowToSong(r: any): CMSSong {
  return {
    id: r.id,
    slug: r.slug,
    title: r.title,
    artistSlug: r.artist_slug,
    artistName: r.artist_name,
    releaseSlug: r.release_slug ?? undefined,
    releaseName: r.release_name ?? undefined,
    producerSlugs: r.producer_slugs ?? undefined,
    genre: r.genre ?? undefined,
    duration: r.duration ?? undefined,
    audioUrl: r.audio_url ?? undefined,
    lyrics: r.lyrics ?? undefined,
    isExplicit: r.is_explicit ?? false,
    trackNumber: r.track_number ?? undefined,
    status: r.status ?? "draft",
    isVisible: r.is_visible ?? false,
    publishAt: r.publish_at ?? undefined,
    featuredOnHomepage: r.featured_on_homepage ?? false,
    mediaAssetId: r.media_asset_id ?? undefined,
    dspLinks: r.dsp_links ?? undefined,
    isrc: r.isrc ?? undefined,
    rightsMetadata: r.rights_metadata ?? undefined,
    dataSource: r.data_source ?? undefined,
    spotifyTrackId: r.spotify_track_id ?? undefined,
    spotifyAudioFeatures: r.spotify_audio_features ?? undefined,
    createdAt: r.created_at,
    updatedAt: r.updated_at,
  };
}
